// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, userID int64) (int64, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error)
	FindProductByID(ctx context.Context, id int64) (Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ReduceProductQuantity(ctx context.Context, arg ReduceProductQuantityParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
