CREATE TABLE IF NOT EXISTS products (
  id   BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name text    NOT NULL,
  price  DECIMAL(10, 2) NOT NULL CHECK (price >= 0),
  quantity INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);